dist: xenial
language: generic
sudo: required

services:
  - docker

env:
  global:
    - QEMUVER=3.1.0-3

before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker -v
  - docker pull arm32v7/alpine:edge
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # - docker ps -a

script:
# get qemu-arm-static binary
  - >
    mkdir tmp &&
    pushd tmp > /dev/null &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v${QEMUVER}/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    pwd && ls -alh &&
    popd > /dev/null &&
    pwd && ls -alh
  - DOCKER_BUILDKIT=1 docker build --progress=plain -t rpix .
  - docker build -t rpix .


after_success:
  # - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  # - export REPO=
  # - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  # - docker build -f Dockerfile -t $REPO:$COMMIT .
  # - docker tag $REPO:$COMMIT $REPO:$TAG
  # - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  # - docker push $REPO